### ISSUE TITLE
Upgrade to libopus 1.3

### ISSUE THREAD

**Issue by 1Jo1** [TyounanMOTI/UnityOpus#1]
it still uses libopus 1.2.1. Opus 1.3 released October which is a major release have some quality improvements.

**Comment by TyounanMOTI** [comment]
Thank you, it will coming soon!

**Comment by TyounanMOTI** [comment]
Updated libopus to current master HEAD (June 5, 2019 ad8fe90db79b7d2a135e3dfd2ed6631b0c5662ab).
Released as UnityOpus 1.1.0. Thank you!
